# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlNotes < Formula
  desc "kubectl extension for working with notes for Kubernetes Pods"
  homepage "https://github.com/lucperkins/kubectl-notes"
  url "https://github.com/lucperkins/kubectl-notes/releases/download/v0.1.2/kubectl-notes_0.1.2_Darwin_x86_64.tar.gz"
  version "0.1.2"
  sha256 "1c7caf913de0efaaf13c891a97dec974161006282d0ee911d268c315f0b81562"

  def install
    bin.install "kubectl-notes"
  end

  test do
    system "#{bin}/kubectl-notes --version"
  end
end
