# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlNotes < Formula
  desc "kubectl extension for working with notes for Kubernetes Pods"
  homepage "https://github.com/lucperkins/kubectl-notes"
  url "https://github.com/lucperkins/kubectl-notes/releases/download/v0.1.21/kubectl-notes_0.1.21_Darwin_x86_64.tar.gz"
  version "0.1.21"
  sha256 "448376dbc14f2e46885d210ce0af82396323c02ac79fb325a08e7db1e5412e54"

  def install
    bin.install "kubectl-notes"
  end

  test do
    system "#{bin}/kubectl-notes --version"
  end
end
